writingthread      = true

writer1            = console
writer1.format     = {level} {date}: {message}
writer1.level      = info
writer1.buffered   = true

writer2            = console
writer2.tag        = sysout
writer2.buffered   = false